project:
  type: book
  output-dir: docs
  render: 
    - "*.qmd"
    # - "*.ipynb"
    - "!aux/"
    
book:
  title: "MachineLearning"
  author: "Yebinpapa"
  date: "3/8/2023"
  page-navigation: true
  chapters:
    - index.qmd 
    - part: src/theory/ML.qmd
      chapters:
        - src/theory/optimization.qmd
        - src/theory/regression.qmd
        - src/theory/statistics.qmd
        - src/theory/classification.qmd
        - src/theory/perceptron_and_ann.qmd
        - src/theory/cnn.qmd
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    fontsize: 0.9em
    toc: true
    number-sections: true



